### PR TITLE
example.cs

### PR DESCRIPTION
**Pull request by 3stripeEli**
this is the test, ChickenDev26

### CODE REVIEW

**Comment by ChickenDev26** [comment]
hi

**Comment by 3stripeEli** [comment]
great chickendev, now we know that you're here

**Comment by ChickenDev26** [comment]
> great chickendev, now we know that you're here

good

**Comment by ChickenDev26** [comment]
`using System;

class MainClass {
  public static void Main (string[] args) {

      Console.WriteLine("Welcome To Pear OS.");
      
  }
}`

**Comment by ChickenDev26** [comment]
lol

**Comment by 3stripeEli** [comment]
You dense motherfucker

**Comment by ChickenDev26** [comment]
> You dense motherfucker

woah calm down brandon, dont pull out the desert eagle

**Pull request merged**
